# Generated by Django 4.2.28 on 2026-08-29 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=30, unique=True, verbose_name='RA')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('turma', models.CharField(blank=True, max_length=20, verbose_name='Turma')),
                ('serie', models.CharField(blank=True, max_length=30, verbose_name='Série')),
                ('escola', models.CharField(blank=True, max_length=50, verbose_name='Escola')),
                ('ativo', models.BooleanField(default=True, help_text='Alunos inativos não podem votar', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, help_text='Conta de login vinculada (username = RA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Tema')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('inicio', models.DateTimeField(verbose_name='Início da votação')),
                ('fim', models.DateTimeField(verbose_name='Fim da votação')),
                ('ativa', models.BooleanField(default=True, help_text='Desative para suspender a votação', verbose_name='Ativa')),
                ('publicar_resultados', models.BooleanField(default=True, help_text='Alunos podem consultar o resultado após o encerramento', verbose_name='Publicar resultados')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eleição / Votação',
                'verbose_name_plural': 'Eleições / Votações',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='votacao.eleicao')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('professor', 'Professor'), ('aluno', 'Aluno')], default='aluno', max_length=20, verbose_name='Nível')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votacao.aluno')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votacao.eleicao')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_rel', to='votacao.opcao')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['criado_em'],
                'unique_together': {('eleicao', 'aluno')},
            },
        ),
    ]
